name:  JDCloud-AX6000-Baili-padavanonly

on: 
  workflow_dispatch:
    inputs:
      LAN_IP:
        description: 'Set LAN IP Address'
        required: true
        default: '192.168.1.1'
#  schedule:
#    - cron: 0 03 * * 2,5

env:
  ###############æ‰‹åŠ¨ä¿®æ”¹##############
  OPENWRT_NAME: padavanonly
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-23.05
  REPO_BRANCH: openwrt-23.05
  FEEDS_CONF: AX6000/JDCloud-AX6000-Baili-padavanonly/feeds.conf.default
  CONFIG_FILE: AX6000/JDCloud-AX6000-Baili-padavanonly/.config
  DIY_P1_SH: AX6000/JDCloud-AX6000-Baili-padavanonly/diy-part1.sh
  DIY_P2_SH: AX6000/JDCloud-AX6000-Baili-padavanonly/diy-part2.sh
  SSH_ACTIONS: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    
    - name: æ£€æŸ¥é¡¹ç›®åˆ†æ”¯
      uses: actions/checkout@main

    - name: æ¸…ç†ç£ç›˜ç©ºé—´
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true        
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
      
    - name: æŸ¥çœ‹æœºå™¨é…ç½®
      run: |
        echo "è­¦å‘Šâš "
        echo "åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½æœ‰é™ï¼Œè‹¥é€‰æ‹©çš„æ’ä»¶è¿‡å¤šï¼ŒåŠ¡å¿…æ³¨æ„CPUæ€§èƒ½ï¼"
        echo -e "CPUæ€§èƒ½æ’åº: 7763 > 8370C > 8272CL > 8171M > E5-2673\n"
        echo "--------------------------CPUä¿¡æ¯--------------------------"
        echo "CPUç‰©ç†æ•°é‡: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUæ ¸å¿ƒæ•°é‡: $(nproc)"
        echo -e "CPUå‹å·ä¿¡æ¯:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------å†…å­˜ä¿¡æ¯--------------------------"
        echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: å®‰è£…ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: å…‹éš†å›ºä»¶æºç 
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: æ·»åŠ å¤–éƒ¨æ’ä»¶
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: æ›´æ–°å¤–éƒ¨æ’ä»¶
      run: cd openwrt && ./scripts/feeds update -a

    - name: è¯»å–å¤–éƒ¨æ’ä»¶
      run: cd openwrt && ./scripts/feeds install -a

    - name: åŠ è½½ä¸ªäººè®¾ç½®
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: è®¾ç½®LAN IPåœ°å€ï¼ˆè·¯ç”±å™¨ç™»å½•åœ°å€ï¼‰
      run: |
        cd openwrt
        SET_IP=${{ github.event.inputs.LAN_IP }}
        if [[ $SET_IP =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then
            #ä¿®æ”¹é»˜è®¤IPåœ°å€
            sed -i "s/192\.168\.[0-9]*\.[0-9]*/$SET_IP/g" package/base-files/files/bin/config_generate
            echo "Set LAN IP Address: $SET_IP"
        else
            echo "Invalid IP address, use default."
        fi
    
    - name: ä¸‹è½½å›ºä»¶dLåº“
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: æ­£åœ¨ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        sed -n 's/.*lan) ipad=${ipaddr:-"\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)"} ;;.*/\1/p' package/base-files/files/bin/config_generate | head -n 1 > IP_ADDR
        [ -s IP_ADDR ] && echo "IP_ADDR=$(cat IP_ADDR)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "FILE_TIME=$(date "+%Yå¹´%mæœˆ%dæ—¥")" >> $GITHUB_ENV
        echo "TAG_TIME=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_ENV

    - name: æŸ¥çœ‹ç£ç›˜ç”¨é‡
      if: (!cancelled())
      run: df -hT

    - name: æ‰“åŒ…æ•´ç†å›ºä»¶
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages && mkdir packages
        find -name "*.manifest*" | xargs -i mv -f {} packages
        find -name "*vmlinuz*" | xargs -i mv -f {} packages
        find -name "*buildinfo*" | xargs -i mv -f {} packages
        find -name "*json*" | xargs -i mv -f {} packages
        find -name "*sha256sums*" | xargs -i mv -f {} packages
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: æ‰“åŒ…ä¸Šä¼ å›ºä»¶
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt-Mini${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: åˆ›å»ºå‘å¸ƒæ ‡ç­¾
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=${{ env.TAG_TIME }}" >> $GITHUB_OUTPUT
        touch release.txt
        echo "ä½¿ç”¨æºç ï¼š${{ env.REPO_URL }}" >> release.txt
        echo "ç®¡ç†åœ°å€ï¼š${{ env.IP_ADDR }}" >> release.txt
        echo "é»˜è®¤å¯†ç ï¼šæ— å¯†ç " >> release.txt
        echo "æ’ä»¶æ¸…å•ï¼šShadowSocksR Plus+ï¼ŒPassWallï¼ŒOpenClash" >> release.txt
        echo "ç”±è¡·æ„Ÿè°¢æ‰€æœ‰ä¸ºopenwrtæ— ç§å¥‰çŒ®çš„å¤§ä½¬ä»¬" >> release.txt
        echo "ğŸ“¥ å›ºä»¶ä¸‹è½½" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: å‘å¸ƒæ–°ç‰ˆå›ºä»¶
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        name: ${{ env.FILE_DATE }}-padavanonly-jdcloud_re-cp-03
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/* 

    - name: æ¸…ç†ç¼–è¯‘æµç¨‹
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 50
        keep_minimum_runs: 10

    - name: åˆ é™¤æ—§ç‰ˆå›ºä»¶
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 10
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
